// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAf61D72GeUHCsnynALVcttqt9i53Qiuy8',
    appId: '1:641693954686:web:05ff9802ab7670ab3e5e2f',
    messagingSenderId: '641693954686',
    projectId: 'technoblog-f8152',
    authDomain: 'technoblog-f8152.firebaseapp.com',
    storageBucket: 'technoblog-f8152.firebasestorage.app',
    measurementId: 'G-K48QGZ34LX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCigA849WydCLaeLF_m9zhwo_M9omCNjRM',
    appId: '1:641693954686:android:2a87c5345d5c32ff3e5e2f',
    messagingSenderId: '641693954686',
    projectId: 'technoblog-f8152',
    storageBucket: 'technoblog-f8152.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1sdXMyUSPCxIZmdGvToGnO0-HYUoGYhE',
    appId: '1:641693954686:ios:9a2a0f83193315d93e5e2f',
    messagingSenderId: '641693954686',
    projectId: 'technoblog-f8152',
    storageBucket: 'technoblog-f8152.firebasestorage.app',
    iosClientId: '641693954686-78ks9pcj2uppu6jv4ue1iaoveur5uvhp.apps.googleusercontent.com',
    iosBundleId: 'com.technoblog.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1sdXMyUSPCxIZmdGvToGnO0-HYUoGYhE',
    appId: '1:641693954686:ios:13eff90fb09d60a63e5e2f',
    messagingSenderId: '641693954686',
    projectId: 'technoblog-f8152',
    storageBucket: 'technoblog-f8152.firebasestorage.app',
    iosClientId: '641693954686-jva4brfsadci2acqjguru1oj7b3vhp0q.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAf61D72GeUHCsnynALVcttqt9i53Qiuy8',
    appId: '1:641693954686:web:a766d3c1858eda7d3e5e2f',
    messagingSenderId: '641693954686',
    projectId: 'technoblog-f8152',
    authDomain: 'technoblog-f8152.firebaseapp.com',
    storageBucket: 'technoblog-f8152.firebasestorage.app',
    measurementId: 'G-DFHZ1GGYFB',
  );

}